### ISSUE TITLE
BrokenPipError occured when calling add function

### ISSUE THREAD

**Issue by makaishi2** [superkerokero/naruhodo#16]
```
from naruhodo import parser
DA = parser(lang="ja", gtype="d")
DA.add("一郎は二郎が描いた絵を三郎に贈った。")
```

and returned

```
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
<ipython-input-3-a2f402b9bf2a> in <module>
      1 # Now we can add some text to it
----> 2 DA.add("一郎は二郎が描いた絵を三郎に贈った。")

~/anaconda3/lib/python3.7/site-packages/naruhodo/core/parser.py in add(self, inp)
    266         if inp == "":
    267             return [inp]
--> 268         self.core.add(inp, self.pos)
    269         self.pos += 1
    270         self.G = _mergeGraph(self.G, self.core.G)

~/anaconda3/lib/python3.7/site-packages/naruhodo/core/DependencyCoreJa.py in add(self, inp, pos)
     35         cabo = CabochaClient()
     36         self.pos = pos
---> 37         cabo.add(self.proc.query(inp), self.pos)
     38         root = "" # Initialize root id.
     39         for chunk in cabo.chunks:

~/anaconda3/lib/python3.7/site-packages/naruhodo/utils/communication.py in query(self, inp)
     43         pattern = r'EOS'
     44         self.proc.stdin.write(inp.encode('utf-8') + six.b('\n'))
---> 45         self.proc.stdin.flush()
     46         result = ""
     47         while True:

BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by makaishi2** [comment]
Sorry, my environment problem.

**Comment by kenkensz9** [comment]
I have the same problem.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ken00\AppData\Roaming\Python\Python36\site-packages\naruhodo\core\parser.py", line 268, in add
    self.core.add(inp, self.pos)
  File "C:\Users\ken00\AppData\Roaming\Python\Python36\site-packages\naruhodo\core\DependencyCoreJa.py", line 37, in add
    cabo.add(self.proc.query(inp), self.pos)
  File "C:\Users\ken00\AppData\Roaming\Python\Python36\site-packages\naruhodo\utils\communication.py", line 45, in query
    self.proc.stdin.flush()
OSError: [Errno 22] Invalid argument`
I would appreciate it if tell how the problem was fixed.

**Comment by superkerokero** [comment]
@kenkensz9 
Your problem sounds like issue #18, you can refer to it for some advice.
